### ISSUE TITLE
UI related: Open Orders, Orders History, and Trade History sorting

### ISSUE THREAD

**Issue by Cryptoford** [Polkadex-Substrate/Oderboook-beta-feedback#12]
![pdex beta orderbook feed1](https://user-images.githubusercontent.com/90802124/152891515-8ba4aa8f-7145-429e-b3a6-c2c62ad14fa5.png)

Hi, although the attached image highlights the orders history tab only, the same can be observed in open orders and trade history.
I suggest resorting (rearranging) of the open orders, order history and trade history tabs to display the most recent activities at the top. This should be more intuitive.

**Comment by simonsso** [comment]
@nuel77  please change

**Comment by nuel77** [comment]
closes with #97
