### ISSUE TITLE
UI: Open sell orders table should be scrolled to the bottom by default

### ISSUE THREAD

**Issue by jmansfie** [Polkadex-Substrate/Oderboook-beta-feedback#17]
Open sell orders table should be scrolled to the bottom by default. 

Traders need be able to see the lowest sell price without having to scroll down each time they open the orderbook.

Current default view:
![image](https://user-images.githubusercontent.com/6218678/153030180-ff5bcacc-5ed1-4238-8597-8c578f4d0c4f.png)

Suggested:
![image](https://user-images.githubusercontent.com/6218678/153030222-a753b5e4-971e-4594-82c2-8635d75b95ac.png)

**Comment by pavankanteti** [comment]
Already implemented
