### ISSUE TITLE
Inconsistency between Order and Trade history

### ISSUE THREAD

**Issue by pdexpab** [Polkadex-Substrate/Oderboook-beta-feedback#19]
Reporter:  Pastashooter

_I found an inconsistency between "Order" and "Trade History". Somehow I managed to sell at 0 price._

![image](https://user-images.githubusercontent.com/89174304/153241700-eba0f66b-57c9-41ee-98e5-25e94a0d3a97.png)
![image](https://user-images.githubusercontent.com/89174304/153241919-0c895101-f423-4ad1-a6db-9fdf45f6ff1f.png)

Response from Gabe:
_It's because market order prices are not showing up in the UI, it's hardcoding 0_

**Comment by pavankanteti** [comment]
Waiting for V2

**Comment by charleslukes** [comment]
fixed in v2
