### ISSUE TITLE
UI related: Price, Amount, and Total title section of orderbook display issue

### ISSUE THREAD

**Issue by Cryptoford** [Polkadex-Substrate/Oderboook-beta-feedback#22]
**Hello,**
there is a small display issue with the above mentioned titled columns when a user scrolls through the open orders. Would be more intuitive if the **display remains static** when scrolling through the list of sell/buy orders. On the current setup, once the user scrolls down the list of orders, the title of each column (i.e Price, Amount, and Total) becomes hidden.
![pdex beta orderbook feed2](https://user-images.githubusercontent.com/90802124/154056592-e4f7229b-3992-45d2-8aad-cc4a7576d3c2.png)

**Comment by simonsso** [comment]
@Cryptoford one observation on your screen size is that is is smaller than what we have checked with internally. Are you running on a small browser window is is this a mobile device?

We will try to modify this component to look good in this environment too.

**Comment by jmansfie** [comment]
@simonsso it's not a screen size issue. He is just asking for you to fix the header row of the table.

So this does not happen:
![image](https://user-images.githubusercontent.com/6218678/154491580-c7ad3e69-a9c0-4a8f-9041-81c521928d0e.png)

These labels should be in a fixed position and not scroll when you scroll the sell or buy tables
![image](https://user-images.githubusercontent.com/6218678/154491762-4086c89a-7b17-447e-a7ed-96d9a792a1e5.png)

**Comment by Cryptoford** [comment]
@jmansfie Correct. you got my point.

**Comment by Cryptoford** [comment]
Hello, @simonsso I'm currently and have always run on a big screen (Laptop currently set at display resolution 1366 x 768). Like @jmansfie commented above, this is more likely not a screen size issue but relates to the header positioning of the highlighted section.

**Comment by charleslukes** [comment]
fixed in v2
