### ISSUE TITLE
UI: Suggestion for the order form inputs

### ISSUE THREAD

**Issue by jmansfie** [Polkadex-Substrate/Oderboook-beta-feedback#23]
Suggestion for the inputs.. make it so the placeholder is always visible. Current view is on the left, suggested is on the right.

![image](https://user-images.githubusercontent.com/6218678/154356160-5ccc4d7b-fffd-4694-a6b8-abdba8a9e0bf.png)

**Comment by charleslukes** [comment]
good observation
