### ISSUE TITLE
Buy order form validation issues

### ISSUE THREAD

**Issue by jmansfie** [Polkadex-Substrate/Oderboook-beta-feedback#4]
There’s something wrong with the validation. See video below.

It won’t let me submit an order for 100 polkadog even though the total price of the order is way less then what I have in shiba. It’s like it’s comparing the total polkadog requested to my shib total, rather then comparing the total cost to my shib total

**Comment by jmansfie** [comment]
https://user-images.githubusercontent.com/6218678/152789984-e4cc9f73-112c-4bad-ab4c-3a00f3ee78ad.mov

**Comment by nuel77** [comment]
closes with https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/pull/97
