### ISSUE TITLE
Column labels in buy/sell tables are not correct

### ISSUE THREAD

**Issue by jmansfie** [Polkadex-Substrate/Oderboook-beta-feedback#5]
The open orders table is showing the wrong token names in the labels I think? Column 1 should be Price(SDX), column 2 should be Amount(PDG). Column 3 label is correct. Same issue on both buy and sell tabl
![unknown](https://user-images.githubusercontent.com/6218678/152790128-257d4d8b-befa-41b1-9e82-c7bf2aaa2f30.png)
e

**Comment by nuel77** [comment]
closes with https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/pull/97

**Comment by pavankanteti** [comment]
Fixed already :)
