### ISSUE TITLE
Total PDG in open sell orders table-- possibly calculated incorrectly?

### ISSUE THREAD

**Issue by jmansfie** [Polkadex-Substrate/Oderboook-beta-feedback#6]
Totals in the sell table are possibly being calculated backwards. Shouldn’t it be the ones i wrote in yellow? If I put a buy order with price 1000, there should be 218.999 available not just 1 I think. The buy order table looks to be correct

![unknown (1)](https://user-images.githubusercontent.com/6218678/152790308-636cabfb-785c-4d56-9ff1-4bfaa2e167d5.png)
t

**Comment by jmansfie** [comment]
It looks like someone fixed this. It can be closed.

**Comment by nuel77** [comment]
closes with https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/pull/97

**Comment by pavankanteti** [comment]
Fixed already :)
