### ISSUE TITLE
Suggestion: Change market order buys to specify how much you want to spend (rather then amount of tokens)

### ISSUE THREAD

**Issue by jmansfie** [Polkadex-Substrate/Oderboook-beta-feedback#8]
It's much more intuitive to provide how much you want to spend when doing market buy.

there are risks with providing amount of tokens you want to market buy without knowing how much it will cost
worst case scenario is that you will spend much more than you wanted
if orderbook depth is not big enough

**Comment by charleslukes** [comment]
done in V2
