### ISSUE TITLE
sell limit order form validation issue

### ISSUE THREAD

**Issue by ddozen** [Polkadex-Substrate/Oderboook-beta-feedback#9]
Bellow you can see that i have 4392  polakadoge and i want to sell 439,2 POLKADOGE for 10 SHIBADEX each
If this order goes through i will receive   4392 SHIBADEX
<img width="320" alt="Screenshot 2022-02-07 at 14 42 03" src="https://user-images.githubusercontent.com/56208130/152800451-1a9704ac-41d8-462e-8b51-eadf432684ca.png">

If i increase number of polkadoge i want to sell by 0,1 to 439,3 validation form disables sell button
<img width="320" alt="Screenshot 2022-02-07 at 14 42 13" src="https://user-images.githubusercontent.com/56208130/152800836-16958740-6694-41cc-bdcf-b875f086f81e.png">

Seems that if number of recived SHIBADEX is larger than amount of available polakdoge the form thinks its not a correct order.
What should happen  is  form should disable sell button only if number available of polkadoge is smaller than value inserted in ammount field.

**Comment by simonsso** [comment]
Duplicate #4

**Comment by nuel77** [comment]
Closes with https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/pull/97
